#
# helix configuration for local development
#

definitions:
  repos:
    - &defaultRepo https://github.com/tripodsan/hlxtest.git#master
    - &contentRepo https://github.com/tripodsan/hlxtest-content.git#master

strains:
  - name: api
    url: https://www.99productrules.com/api/general
    code: *defaultRepo
    content: *contentRepo
    static: *defaultRepo

  - name: default
    url: https://www.99productrules.com
    code: *defaultRepo
    content: *defaultRepo
    static: *defaultRepo
