#
# helix configuration for local development
#

definitions:
  repos:
    - &myRepo https://github.com/tripodsan/hlxtest.git#master

strains:
  default:
    content: *myRepo
    code: *myRepo
    static: *myRepo
