#
# helix configuration for local development
#

definitions:
  repos:
    - &myRepo https://github.com/tripodsan/hlxtest.git#master
    - &myFooRepo https://github.com/tripodsan/hlxtest.git#foo/bar
    - &defaultRepo "http://localhost/local/default.git"

strains:
  dev-subtest:
    url: http://localhost:3000/api/general
    code: *defaultRepo
    content: *defaultRepo
    static: *defaultRepo

  dev:
    url: http://localhost:3000/
    code: *defaultRepo
    content: *defaultRepo
    static: *defaultRepo

  dev-ip:
    url: http://127.0.0.1:3000/
    code: *defaultRepo
    content: *defaultRepo
    static: *defaultRepo

  subtest:
    url: https://www.99productrules.com/api/general
    code: *myRepo
    content: *myFooRepo
    static: https://github.com/tripodsan/hlxtest.git/htdocs#master
    params:
      - a
      - foo
    package: tripod/github-com--tripodsan--hlxtest--master-dirty

  default:
    code: *myRepo
    content: *myRepo
    static: https://github.com/tripodsan/hlxtest.git/htdocs#master
    params:
      - a
      - foo
    package: tripod/github-com--tripodsan--hlxtest--master-dirty

