#
# helix configuration for local development
#

# title of this project. not really needed
title: 'hlxtest'

# Specifies the git url to the content repository. helix will use the local directory if
# not configured.
#
default:
  content:
    repo: hlxtest
    ref: master
    owner: tripodsan
  static:
    repo: hlxtest
    ref: master
    owner: tripodsan
    path: /webroot
