#
# helix configuration for local development
#

definitions:
  repos:
    - &defaultRepo https://github.com/tripodsan/hlxtest.git#master
    - &contentRepo https://github.com/tripodsan/hlxtest-content.git#master

strains:
  - name: api
    url: https://www.99productrules.com/api
    code: *defaultRepo
    content: https://github.com/tripodsan/hlxtest.git/docs#master
    static: https://github.com/tripodsan/hlxtest.git/htdocs#master
    package: tripod/github-com--tripodsan--hlxtest--master-dirty
    directoryIndex: introduction.html

  - name: stage
    url: https://www.99productrules.com/api
    code: *defaultRepo
    content: https://github.com/tripodsan/helix-publish.git/docs#master
    static: https://github.com/tripodsan/hlxtest.git/htdocs#master
    package: tripod/github-com--tripodsan--hlxtest--master-dirty
    directoryIndex: introduction.html

  - name: help
    url: https://www.99productrules.com/help
    code: *defaultRepo
    content: *contentRepo
    static: https://github.com/tripodsan/hlxtest.git/htdocs#master
    package: tripod/github-com--tripodsan--hlxtest--master-dirty
    directoryIndex: introduction.html

  - name: default
    url: https://www.99productrules.com/
    code: *defaultRepo
    content: *defaultRepo
    static: https://github.com/tripodsan/hlxtest.git/htdocs#master
    package: tripod/github-com--tripodsan--hlxtest--master-dirty
