name: Auto Approve

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve on ${{ github.head_ref }}
        # only run on releases/*
        # Note: for some reason limiting the branches in the 'on' above doesn't work
        #if: startsWith(github.head_ref, 'releases/')
        uses: adobe-rnd/github-automerge-action
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
