name: WIP

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  block_label:
    runs-on: ubuntu-latest
    name: Check for label
    steps:
      - name: Trigger
        id: trigger
        uses: adobe-rnd/github-label-wip-action
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          label: breaking

